### ISSUE TITLE
Can't load seed data

### ISSUE THREAD

**Issue by wimglenn** [kevinreedy/shuffio#89]
`rake db:setup` not working - maybe schema changed and `seeds/teams.rb` need to updated for new columns e.g. captain?  or might be just me being idiot?

also - could please provide a recent db dump for use with dev instance?

tail of trace below 

```
...
-- add_foreign_key("divisions", "seasons")
   -> 0.0038s
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Captain can't be blank
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/validations.rb:80:in `raise_validation_error'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/validations.rb:52:in `save!'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:315:in `block in save!'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/transactions.rb:315:in `save!'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/suppressor.rb:48:in `save!'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/persistence.rb:53:in `create!'
/Users/wim/src/shuffio/db/seeds/teams.rb:75:in `<top (required)>'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/Users/wim/src/shuffio/db/seeds.rb:2:in `block in <top (required)>'
/Users/wim/src/shuffio/db/seeds.rb:1:in `each'
/Users/wim/src/shuffio/db/seeds.rb:1:in `<top (required)>'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/engine.rb:551:in `load_seed'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/Users/wim/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

**Comment by kevinreedy** [comment]
@wimglenn I somehow missed your issues. Sorry about that! I'll get to them after banquet.

I'm cooking up something fun for banquet, a /live endpoint that shows the live results of two games. Let me know if you have time to help out this week. I'll be documenting issues over in https://github.com/kevinreedy/shuffio/milestone/1.
